name: masjid_alarm_app
description: "Masjid Namaz Alarm App - prayer time alerts from your selected masjid."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0
  audioplayers: ^5.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  permission_handler: ^11.3.1
  url_launcher: ^6.3.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  android_intent_plus: ^5.2.0
  flutter_timezone: ^3.0.0
  flutter_foreground_task: ^8.13.0
  shared_preferences: ^2.3.2
  flutter_compass: ^0.7.0
  flutter_overlay_window: ^0.4.5
  hijri: ^3.0.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mosque_header.jpg
    - assets/images/quran_artwork.jpg
    - assets/images/kaaba_qibla.jpg
    - assets/quran/quran_en.json
    - assets/quran/quran_ur.json
    - assets/quran/quran_hi_lookup.json
    - assets/hadith/eng_bukhari.json
    - assets/hadith/urd_bukhari.json
    - assets/hadith/ara_bukhari.json
    - assets/hadith/eng_muslim.json
    - assets/hadith/urd_muslim.json
    - assets/hadith/ara_muslim.json
    - assets/hadith/eng_abudawud.json
    - assets/hadith/urd_abudawud.json
    - assets/hadith/ara_abudawud.json
    - assets/hadith/eng_tirmidhi.json
    - assets/hadith/urd_tirmidhi.json
    - assets/hadith/ara_tirmidhi.json
    - assets/hadith/eng_nasai.json
    - assets/hadith/urd_nasai.json
    - assets/hadith/ara_nasai.json
    - assets/hadith/eng_ibnmajah.json
    - assets/hadith/urd_ibnmajah.json
    - assets/hadith/ara_ibnmajah.json
